angular.module(
  'wbooks',
  [
    'pathgather.popeye',
    'ui.router',
    'LocalStorageModule',
    'pascalprecht.translate',
    'ngMessages',
    'ngMaterial',
    'pascalprecht.translate'
  ]
);
